//Refs
export const {
  backdrop,
  cocktailModalMain,
  ingrModalMain,
  modalIngr,
  modalIngrBtnClose,
  modalIngrWrapper,
  modalWrapper,
  ingrCloseBnt,
  cocktailsList,
  cocktailsListCloseBtn,
  letterList,
  heroButtonRef,
  heroSelectRef,
  titleCocktails,
  btnLoadMore,
  btnLogIn,
  btnFavCoks,
  btnFavIngr,
  sectionHero,
} = {
  backdrop: document.querySelector('[data-modal]'),
  cocktailModalMain: document.querySelector('.btn__learn-more__modal'),
  ingrModalMain: document.querySelector('.cocktails-ingredients-modal'),
  modalIngr: document.querySelector('.cocktails-ingredients-modal'),
  modalIngrBtnClose: document.querySelector('.ingr-close-btn'),
  modalIngrWrapper: document.querySelector(
    '.cocktails-ingredients-modal__wrapper'
  ),
  modalWrapper: document.querySelector('.modal__wrapper'),
  ingrCloseBnt: document.querySelector('.ingr-close-btn'),
  cocktailsListCloseBtn: document.querySelector(
    '.btn__learn-more__modal__close__btn'
  ),
  cocktailsList: document.querySelector('.cocktails__list'),
  letterList: document.querySelector('.hero__list'),
  heroButtonRef: document.querySelector('.hero__list'),
  heroSelectRef: document.querySelector('[name="search"]'),
  titleCocktails: document.querySelector('.cocktails__title'),
  btnLoadMore: document.querySelector('.btn_load-more'),
  btnLogIn: document.querySelector('.btn-login'),
  btnFavCoks: document.querySelector('[data-action="link-fav-cock"]'),
  btnFavIngr: document.querySelector('[data-action="link-fav-ingr"]'),
  sectionHero: document.querySelector('.hero'),
};
